global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s 


scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ["https://www.gastrocarta.net", "http://www.prometheus.io"]