global:
  scrape_interval: 15s # default 1m
  evaluation_interval: 15s # default 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ['workernode:9100']
