apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules.yml: |-
    # Rules

  prometheus.yml: |-
    global:
      scrape_interval: 20s # default 1m

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      
      - job_name: k8s-nodes
        scheme: https 
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node

      - job_name: k8s-hw-app-services
        kubernetes_sd_configs:
          - role: service 
            namespaces:
              names: 
                - hwns 

      - job_name: node-balancer
        file_sd_configs:
          - files: 
            - targets.yml

  targets.yml: |-
    - labels: 
        job: node-balancer
      targets:
        - 10.0.0.13:9100