global:
  scrape_interval: 20s

scrape_configs: 
  - job_name: 'prometheus'
    static_configs: 
    - targets: ['localhost:9090']

  - job_name: 'linuxbatch'
    static_configs: 
    - targets: ['linux-batch:9100']

  - job_name: 'batch'
    static_configs: 
    - targets: ['linux-batch:8080']

  - job_name: 'linuxweb'
    scrape_timeout: 15s
    static_configs: 
    - targets: ['linux-web:9100']

  - job_name: 'web'
    metrics_path: /metrics
    static_configs: 
    - targets: ['linux-web:8080']